# Generated by Django 4.2 on 2023-05-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestion",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="suggestion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
